all:
		cd ../ ; /ACG/acgdev/bin/acgmake -comp=gcc-4.2 -j4 -max
		echo done.
clean:
		/ACG/acgdev/bin/acgmake allclean
dist:
		/ACG/acgdev/bin/acgmake -max -dist
rebuild:
		/ACG/acgdev/bin/acgmake allclean
		/ACG/acgdev/bin/acgmake -max
debug:
		/ACG/acgdev/bin/acgmake
debug-dist:
		/ACG/acgdev/bin/acgmake -dist
                                    
