REM Add the cmake path
set PATH=%PATH%;C:\Program Files (x86)\CMake\bin\

REM Run tests from toplevel build dir
cd ..

REM Delete old test results which are generated by OpenFlipper
del /Q tests\testResults\*

REM Delete old test result collection generated by ctest
del /Q CTestResults.xml

REM Run the tests
ctest -D ExperimentalTest -C Release --no-compress-output

REM Call head on the TAG to get the current folder where the test results are
FOR /F "tokens=1 delims= " %%i IN ('tests\head.bat 1 Testing\TAG') DO @set result=%%i 

REM Go into that folder
cd Testing
cd %result%

REM copy generated xml results file to the location where jenkins expects it
copy /Y Test.xml ..\..\CTestResults.xml

REM Go back to start directory
REM cd ..
REM cd ..
