REM Delete old test results which are generated by OpenFlipper
del /Q testResults\*

REM Delete old test result collection generated by ctest
del /Q ..\CTestResults.xml

REM Run the tests
ctest -D ExperimentalTest -C Release --no-compress-output

REM Call head on the TAG to get the current folder where the test results are
FOR /F "tokens=1 delims= " %%i IN ('head.bat 1 Testing\TAG') DO @set result=%%i 

REM Go into that folder
cd Testing
cd %result%

REM copy generated xml results file to the location where jenkins expects it
copy /Y Test.xml ..\..\..\CTestResults.xml

REM Go back to start directory
cd ..
cd ..
