# - Try to find BASESHAPE2D
# Once done this will define
#  
#  BASESHAPE2D_FOUND        - system has BaseShape2D
#  BASESHAPE2D_INCLUDE_DIR  - the BaseShape2D include directory
#  BASESHAPE2D_LIBRARY_DIR  - where the libraries are
#  BASESHAPE2D_LIBRARY      - Link these to use BaseShape2D
#   

IF (BASESHAPE2D_INCLUDE_DIR)
  # Already in cache, be silent
  SET(BASESHAPE2D_FIND_QUIETLY TRUE)
ENDIF (BASESHAPE2D_INCLUDE_DIR)

FIND_PATH( BASESHAPE2D_INCLUDE_DIR BaseShape2D/BaseShape2DDefines.hh
           PATHS "${CMAKE_SOURCE_DIR}/libs/" )

add_definitions (-DBASESHAPE2DDLL -DUSEBASESHAPE2D )

IF (BASESHAPE2D_INCLUDE_DIR)
  SET(BASESHAPE2D_FOUND TRUE)
  SET( BASESHAPE2D_LIBRARY_DIR "${CMAKE_BINARY_DIR}/Build/${ACG_PROJECT_LIBDIR}" )
  SET( BASESHAPE2D_LIBRARY "BaseShape2D")
ELSE (BASESHAPE2D_INCLUDE_DIR)
  SET( BASESHAPE2D_FOUND FALSE )
  SET( BASESHAPE2D_LIBRARY_DIR )
ENDIF (BASESHAPE2D_INCLUDE_DIR)

